Fixed namespace propagation after dom manipulation
jindw/xmldom pull request #216
Opened 2017-07-07 14:44 UTC by tobiasso85

When DOM is manipulated the namespace gets correctly propagated to all
children if their namespace was declared in the removed node instead of
only the first child.

2017-09-16 08:52 UTC, edi9999 requested changes

2017-09-16 08:52 UTC, edi9999 commented on readme.md
> ->npm install xmldom
This shouldn't be in your pull request

2017-09-16 08:52 UTC, edi9999 commented on package.json
> -  "homepage": "https://github.com/jindw/xmldom",
This shouldn't be in your PR

2017-09-16 08:52 UTC, edi9999 commented on dom.js
> +		return buf.push(' ',node.name,'="',String(node.value).replace(/[<&"]/g,_xmlEncoder),'"');
Why did you add String ?

2017-09-16 08:52 UTC, edi9999 commented on test/dom/serializer.js
> +		//console.log(doc.documentElement.firstChild.toString(true))
Can you remove this console.log ?

2017-09-19 10:59 UTC, tobiasso85 commented
continued pull request with #221 to have it completely separate

2017-09-19 10:59 UTC, closed without merging